from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
import mysql.connector
from mysql.connector import Error

class Ui_InformationWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 838, 541))
        self.groupBox.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(110, 30, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 70, 181, 431))
        self.groupBox_3.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(100, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 70, 60))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(r"C:\Users\Win10\Desktop\Data_UTV\Code\icon\thong_tin_ND.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 130, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 170, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 210, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 400, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 90, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 70, 611, 431))
        self.groupBox_2.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(50, 80, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(50, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(50, 180, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(50, 230, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(50, 280, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        # QLineEdit để nhập thông tin
        self.lineEdit_name = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_name.setGeometry(QtCore.QRect(170, 70, 221, 31))
        self.lineEdit_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_name.setObjectName("lineEdit_name")

        self.lineEdit_dob = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_dob.setGeometry(QtCore.QRect(170, 120, 221, 31))
        self.lineEdit_dob.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dob.setObjectName("lineEdit_dob")

        self.lineEdit_address = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_address.setGeometry(QtCore.QRect(170, 170, 221, 31))
        self.lineEdit_address.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_address.setObjectName("lineEdit_address")

        self.lineEdit_phone = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_phone.setGeometry(QtCore.QRect(170, 220, 221, 31))
        self.lineEdit_phone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_phone.setObjectName("lineEdit_phone")

        self.lineEdit_id = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_id.setGeometry(QtCore.QRect(170, 270, 221, 31))
        self.lineEdit_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_id.setObjectName("lineEdit_id")

        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(220, 330, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Kết nối nút "Lưu thông tin" với hàm save_information
        self.pushButton.clicked.connect(self.save_information)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_14.setText(_translate("MainWindow", "HỆ THỐNG CHẨN ĐOÁN VÀ GIẢI PHÁP BỆNH UNG THU VÚ"))
        self.label_4.setText(_translate("MainWindow", "Menu"))
        self.pushButton_7.setText(_translate("MainWindow", "Chẩn đoán bệnh"))
        self.pushButton_8.setText(_translate("MainWindow", "Hồ sơ bệnh án"))
        self.pushButton_9.setText(_translate("MainWindow", "Đề xuất giải pháp"))
        self.pushButton_10.setText(_translate("MainWindow", "Đăng xuất"))
        self.pushButton_11.setText(_translate("MainWindow", "Thông tin bệnh nhân"))
        self.label_7.setText(_translate("MainWindow", "Họ và tên:"))
        self.label_8.setText(_translate("MainWindow", "Ngày sinh:"))
        self.label_9.setText(_translate("MainWindow", "Địa chỉ:"))
        self.label_10.setText(_translate("MainWindow", "Số điện thoại:"))
        self.label_11.setText(_translate("MainWindow", "CMND/CCCD:"))
        self.pushButton.setText(_translate("MainWindow", "Lưu thông tin"))

    def save_information(self):
        name = self.lineEdit_name.text()
        dob = self.lineEdit_dob.text()
        address = self.lineEdit_address.text()
        phone = self.lineEdit_phone.text()
        id_number = self.lineEdit_id.text()

        try:
            dob = datetime.strptime(dob, '%d/%m/%Y').strftime('%Y-%m-%d')
        except ValueError:
            QtWidgets.QMessageBox.warning(None, 'Error', 'Vui lòng nhập đúng định dạng ngày sinh: DD/MM/YYYY')
            return

        try:
            conn = mysql.connector.connect(
                host='localhost',
                database='patients_info',
                user='root',
                password='Weak'
            )

            if conn.is_connected():
                cursor = conn.cursor()
                cursor.execute('''INSERT INTO patients (name, dob, address, phone, id_number) 
                                  VALUES (%s, %s, %s, %s, %s)''', (name, dob, address, phone, id_number))
                conn.commit()
                QtWidgets.QMessageBox.information(None, 'Success', 'Thông tin đã được lưu thành công!')
        except Error as e:
            QtWidgets.QMessageBox.critical(None, 'Error', f'Error connecting to MySQL: {e}')
        finally:
            if conn.is_connected():
                cursor.close()
                conn.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_InformationWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
